[workspace]
authors = ["Mauro Silberberg <maurosilber@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
name = "binlets-spectral"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib = "*"
numpy = "*"
scipy = "*"
